development:
  adapter: mysql2
  database: artchart_dev
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: artchart_test
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: artchart_prod
  pool: 5
  timeout: 5000
